name: Pico OS CI

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # <--- Pull FreeRTOS
          fetch-depth: 0  # <--- Download all tags and historics.

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build gcc

      - name: Run Unit Tests
        run: |
          # Compile the test using the standard Linux GCC
          gcc ./src/main.c ./test/test_main.c ./unity/unity.c -I ./unity/ -I ./src/ -DUNIT_TEST -o run_tests
          ./run_tests

      - name: Setup Pico SDK
        run: |
          # Clone the SDK and initialize submodules
          git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk
          echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV
          cd $HOME/pico-sdk && git submodule update --init

      - name: Build Firmware (.uf2)
        run: |
          mkdir build
          cd build
          # Configure and build using Ninja
          cmake .. -G Ninja
          cmake --build .